// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC56HdoCFhJSSu_E0rqjbTgOk1Ym8TXn4c',
    appId: '1:865033319998:web:ce2fe84a822830f3a7c36f',
    messagingSenderId: '865033319998',
    projectId: 'anket-uygulamasi-8e110',
    authDomain: 'anket-uygulamasi-8e110.firebaseapp.com',
    databaseURL: 'https://anket-uygulamasi-8e110-default-rtdb.firebaseio.com',
    storageBucket: 'anket-uygulamasi-8e110.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqeiMP8E3qP8f-Yz76ndehbJQOVAu1UZ4',
    appId: '1:865033319998:android:79cbf4f778618b12a7c36f',
    messagingSenderId: '865033319998',
    projectId: 'anket-uygulamasi-8e110',
    databaseURL: 'https://anket-uygulamasi-8e110-default-rtdb.firebaseio.com',
    storageBucket: 'anket-uygulamasi-8e110.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl8GhEpBGWvBr9fuXcagay-pJ4VnWf6SQ',
    appId: '1:865033319998:ios:4604332b82270c39a7c36f',
    messagingSenderId: '865033319998',
    projectId: 'anket-uygulamasi-8e110',
    databaseURL: 'https://anket-uygulamasi-8e110-default-rtdb.firebaseio.com',
    storageBucket: 'anket-uygulamasi-8e110.appspot.com',
    iosClientId: '865033319998-q7hbea1ehos2m5eladjvk3jrig473i86.apps.googleusercontent.com',
    iosBundleId: 'com.yunusemrekaplan.anketApp',
  );
}
